Feature/#104 behavior subject
icapps/flutter-icapps-architecture pull request #105
Opened 2023-09-26 14:48 UTC by jorre127

fixes #104

2023-09-27 09:36 UTC, ikbendewilliam commented on test/util/streams/stream_with_initial_value_test.dart
> +    test('Test stream without value in constructor', () {
*With

2023-09-27 09:39 UTC, ikbendewilliam commented on test/util/streams/stream_with_initial_value_test.dart
> +    });
```
    test('Test stream with multiple value', () {
      final streamController = StreamControllerWithInitialValue<int>();
      var testValue = 1;
      streamController.add(testValue);
      streamController.listen((value) {
        expect(value, testValue);
      });
      testValue = 2;
      streamController.add(testValue);
      expect(streamController.value, testValue);
      testValue = 3;
      streamController.add(testValue);
      expect(streamController.value, testValue);
      streamController.close();
    });
```

2023-09-28 13:49 UTC, vanlooverenkoen requested changes

2023-09-28 13:49 UTC, vanlooverenkoen commented on example/lib/screen/counter_screen.dart
> +              Text(
can you add another test with a streambuilder?

2023-10-02 08:50 UTC, ikbendewilliam submitted a review, later dismissed

2023-10-02 09:12 UTC, merged