Feature/ios touch feedback
icapps/flutter-icapps-architecture pull request #116
Opened 2024-02-21 13:41 UTC by jorre127

2024-02-22 10:15 UTC, ikbendewilliam requested changes
Channge major version + update documentation & changelog

2024-02-22 10:15 UTC, ikbendewilliam commented on lib/src/widget/touch_feedback/touch_feedback.dart
> +            (isAndroid
Also add a light and dark version for android

2024-02-22 10:15 UTC, ikbendewilliam commented on lib/src/widget/touch_feedback/touch_feedback.dart
> +  const TouchFeedBack.dark({
Don't use named constructors here, there are to many options IMO

2024-02-22 10:15 UTC, ikbendewilliam commented on lib/src/widget/touch_feedback/touch_feedback.dart
> +        touchEffectBuilders: [
Make it possible to provide custom `touchEffectBuilders`

2024-02-23 08:41 UTC, ikbendewilliam requested changes

2024-02-23 08:41 UTC, ikbendewilliam commented on CHANGELOG.md
> +-  Updated touchfeedback for ios to be more inline with the specs.
breaking change -> version `2.2.0`
Add breaking: `onClick` becomes `onTapped`
Removed BetterInkwell widget + explain how to use it now
`TouchFeedBack ` & `iOS` to be more inline with the native look and feel
Added option to specify custom effects

2024-02-23 12:44 UTC, ikbendewilliam commented on pubspec.yaml
> +version: 2.1.6
Also update this to 2.2.0 😅

2024-02-23 13:19 UTC, jorre127 commented on pubspec.yaml
> +version: 2.1.6
Ah damn I was thinking don't forget to update this while updating the changelog haha

2024-02-23 13:45 UTC, ikbendewilliam approved these changes

2024-02-23 13:45 UTC, merged